### PR TITLE
Fix crash in replication logic when removing logs from interval.

### LINKED ISSUE #931: zenohd crushed after receiving several messages
### Describe the bug

I'm running one zenohd instance and sending several messages with z_put.py , no any additional connections.
backtrace and sh script for reproduce in attachment

### To reproduce

1. Start zenohd : RUST_BACKTRACE=1 ./zenohd -c ../configs/router_second.json5
2. run script: ./m_put_reproduce.sh
[bug.tar.gz](https://github.com/eclipse-zenoh/zenoh/files/14960206/bug.tar.gz)

### System info

Ubuntu 22.04.4 LTS
zenoh main branch 56a44457aac962ba23fbca2f2f9daa663885c4e6
build with cargo build --package zenoh-plugin-storage-manager --package zenohd --profile fast

### PR DESCRIPTION
**Pull request by pftbest**
Fixes #931

### CODE REVIEW

File: plugins/zenoh-plugin-storage-manager/src/replica/digest.rs [hunk 1]
```diff
@@ -492,9 +494,12 @@ impl Digest {
...
                     .retain(|x| {
-                        x.timestamp.get_time() != entry.timestamp.get_time()
-                            && x.timestamp.get_id() != entry.timestamp.get_id()
-                            && x.key != entry.key
+                        let timestamp_identical =
+                            x.timestamp.get_time() == entry.timestamp.get_time() &&
+                            x.timestamp.get_id() == entry.timestamp.get_id();
+                        let key_identical = x.key == entry.key;
+                        let element_identical = timestamp_identical && key_identical;
+                        !element_identical
```
Comment (J-Loudet) [inline plugins/zenoh-plugin-storage-manager/src/replica/digest.rs:502]: This could be simplified like so:
```suggestion
                        x.timestamp != entry.timestamp || x.key != entry.key
```

**Review by J-Loudet — CHANGES_REQUESTED** [review]
Hi @pftbest, thank you for your contribution!

I have one minor suggestion to your PR (although the suggestion could have been applied on our code…). I have tested the reported issue and can no longer reproduce it after your changes.

File: plugins/zenoh-plugin-storage-manager/src/replica/digest.rs (hunk 1 above)
Comment (pftbest) [reply plugins/zenoh-plugin-storage-manager/src/replica/digest.rs]: Done

**Comment by fuzzypixelz** [comment]
> clippy segfaulted :/

That's okay, it will be fixed when merging #935.

**Review by J-Loudet — APPROVED** [review]
