### PR TITLE
fix(1059): adding explicit plugin id in PluginStatus and PluginManager

### LINKED ISSUE #1059: [BUG] Spawning more volumes with the same backend is not reflected in admin space
### Describe the bug

When configuring zenoh to use the same backend for more than a volume, only one of the volume is exposed in the admin space.

### To reproduce

Start a zenoh router with two volumes of the same backend configured:

```json
 "file-system-volume": {
                    "backend": "filesystem_backend"
                },
                "file-system-volume2": {
                    "backend": "filesystem_backend"
                },
```

perform a get on `@/router/*/status/plugins/storage_manager/volumes/*`

the result will show only one `filesystem_backend` volume instead of two.

```json

[
    {
        "key": "@/router/8f2aef5a89c14100b70184094f5bdea9/status/plugins/storage_manager/volumes/filesystem_backend",
        "value": {
            "root": "/home/vscode/.zenoh/zenoh_backend_fs",
            "version": "0.11.0-dev"
        },
        "encoding": "application/json",
        "time": "None"
    }
]
```

the issue comes from this line: https://github.com/eclipse-zenoh/zenoh/blob/main/plugins/zenoh-plugin-storage-manager/src/lib.rs#L322 where the `name` of the plugin (the backend in this case), is used to craft the kexpr.

There is no way currently to get the `id` of the plugin(backend) from the current PluginsManager.

### System info

Any platform
zenoh 0.11.0-rc.3 and previous

### PR DESCRIPTION
**Pull request by gabrik**
This PR adds the `id()` method to the `PluginStatus` trait and allows passing it as a parameter in the `PluginManager` when dynamic loading or statically linking a plugin.
It exposes plugins in the admin space via their ID (see below what the ID is), and allows multiple instances of the same plugin with different configurations, essential for backends, and useful for other plugins.

Changes to configuration:
```json
        "rest2": { // plugin id, used in admin space, to retrieve plugin config
            "__required__": true,
            "http_port": 8000,
            "__plugin__":"rest", // plugin name used in libloading
        },
```

Sister PRs:
- [ ] MQTT: https://github.com/eclipse-zenoh/zenoh-plugin-mqtt/pull/110
- [ ] DDS: https://github.com/eclipse-zenoh/zenoh-plugin-dds/pull/245
- [ ] ROS2 https://github.com/eclipse-zenoh/zenoh-plugin-ros2dds/pull/156
- [ ] WebServer https://github.com/eclipse-zenoh/zenoh-plugin-webserver/pull/85

Sister PRs for testing, do not need a merge.
- [ ] FS Backend https://github.com/eclipse-zenoh/zenoh-backend-filesystem/pull/113
- [ ] RocksDB Backend https://github.com/eclipse-zenoh/zenoh-backend-rocksdb/pull/100
- [ ] S3 https://github.com/eclipse-zenoh/zenoh-backend-s3/pull/82
- [ ] Influx https://github.com/eclipse-zenoh/zenoh-backend-influxdb/pull/121

Closes #1059

### CODE REVIEW

**Comment by gabrik** [comment]
FYI: I see too many unwraps in the `PluginManager` implementation, it is true that they should never fail as they are calls to `Vec::last` after a `Vec::insert` but I think they should not be there anyway.

**Comment by gabrik** [comment]
Note: Lint is failing on a file that has not been touched by the PR.

**Review by Mallets — APPROVED** [review]

**Comment by Mallets** [comment]
The PR looks good to me. 
@gabrik should we wait merging it till all sister PRs are made?

**Comment by gabrik** [comment]
> The PR looks good to me. @gabrik should we wait merging it till all sister PRs are made?

I'm opening the sister PRs and tagging people for review, the ones not to be merged are going to be closed.

**Comment by gabrik** [comment]
Once the sisters are approved then I'm going to merge everything.

File: plugins/zenoh-plugin-trait/src/manager.rs [hunk 1]
```diff
@@ -99,7 +106,7 @@ impl<StartArgs: PluginStartArgs, Instance: PluginInstance> DeclaredPlugin<StartA
 pub struct PluginsManager<StartArgs: PluginStartArgs, Instance: PluginInstance> {
     default_lib_prefix: String,
     loader: Option<LibLoader>,
-    plugins: Vec<PluginRecord<StartArgs, Instance>>,
+    plugins: HashMap<String, PluginRecord<StartArgs, Instance>>,
```
Comment (milyin) [inline plugins/zenoh-plugin-trait/src/manager.rs:109]: `Vec` instead of `HashMap` was chosen because each plugin already knows it's unique name so it was excessive to store this name outside. As far as I see nothing changed, there is just `id` instead of `name`. Is there any particular reason to switch to `HashMap` ?
Storing plugins in `Vec` may become useful in hypothetical situation when plugins depends on each other and loading order is important. Though yes, at this moment choice between `Vec` and `HashMap` here is just a question of personal taste.

File: commons/zenoh-config/src/lib.rs [hunk 2]
```diff
@@ -1021,6 +1021,7 @@ fn load_external_plugin_config(title: &str, value: &mut Value) -> ZResult<()> {
 #[derive(Debug, Clone)]
 pub struct PluginLoad {
     pub name: String,
```
Comment (milyin) [inline commons/zenoh-config/src/lib.rs:1023]: In fact, `name` and `paths`have the same purpose: it's a information for loader where to look for corresponding plugin DLL. Probably the `name` should near the `paths` and be optional also

File: plugins/zenoh-plugin-trait/src/manager.rs [hunk 3]
```diff
@@ -155,38 +170,46 @@ impl<StartArgs: PluginStartArgs + 'static, Instance: PluginInstance + 'static>
         tracing::debug!("Declared dynamic plugin {} by name {}", &name, &plugin_name);
         let loader = DynamicPlugin::new(
             name,
+            id.clone(),
             DynamicPluginSource::ByName((libloader, plugin_name)),
             required,
         );
-        self.plugins.push(PluginRecord::new(loader));
-        Ok(self.plugins.last_mut().unwrap())
+        self.plugins.insert(id.clone(), PluginRecord::new(loader));
```
Comment (milyin) [inline plugins/zenoh-plugin-trait/src/manager.rs:177]: No protection against adding plugin with the same name. Before it was wrong also: same-named plugin was added, but it wasn't possible to access it by name later. Now the old one is just silently removed

File: plugins/zenoh-plugin-trait/src/manager.rs [hunk 4]
```diff
@@ -60,6 +62,11 @@ impl<StartArgs: PluginStartArgs, Instance: PluginInstance> PluginStatus
     fn name(&self) -> &str {
```
Comment (milyin) [inline plugins/zenoh-plugin-trait/src/manager.rs:62]: I'm not sure that after this update we need this `name` getter at all. If plugin is dynamic, the `path()` getter gives us full information where this plugin came from. If it's static, name and id is the same thing.

**Review by milyin — CHANGES_REQUESTED** [review]
This will work ok, but later some refactoring is needed I think, as the `name` became mostly unnecessary.
The parameters of methods should be renamed (`name` -> `id`)

File: plugins/zenoh-plugin-trait/src/manager.rs (hunk 4 above)
Comment (gabrik) [reply plugins/zenoh-plugin-trait/src/manager.rs:62]: The former is true, while not the latter, the user can statically link the plugin once, but instantiate it multiple times with different IDs.

**Review by milyin — APPROVED** [review]
