### PR TITLE
make interceptor-rejected queries and liveliness queries return an empty reply instead of timeout

### LINKED ISSUE #1779: Access Control causes timeout on intercepted requests
### Describe the bug

Using ACL to block request messages causes the instance performing the request to timeout on the handling of the expected responses. Ideally a blocked request should instantly resolve to an empty response, simulating the absence of destinations. This applies to `query` and `liveliness_query` messages.

### To reproduce

Deny in egress a `query` or a `liveliness_query` message. The instance will wait until a timeout then log an error.

### System info

Zenoh 1.2.1
All platforms

### PR DESCRIPTION
**Pull request by DenisBiryukov91**
make interceptor-rejected queries and liveliness queries return an empty reply instead of timeout
Resolves #1779

### CODE REVIEW

File: zenoh/tests/acl.rs [hunk 1]
```diff
@@ -1748,3 +1738,200 @@ async fn test_liveliness_deny_allow_query(port: u16) {
...
+        .insert_json5(
+            "access_control",
+            r#"{
+            "enabled": true,
+            "default_permission": "allow",
+            "rules": [
+                {
+                    "id": "deny query egress",
+                    "permission": "deny",
+                    "messages": ["query", "liveliness_token", "liveliness_query"],
```
Comment (oteffahi) [inline zenoh/tests/acl.rs:1899]: `"query"` and `"liveliness_token"` messages are not related to this test
```suggestion
                    "messages": ["liveliness_query"],
```

File: zenoh/tests/acl.rs [hunk 2]
```diff
@@ -1748,3 +1738,200 @@ async fn test_liveliness_deny_allow_query(port: u16) {
...
+        .insert_json5(
+            "access_control",
+            r#"{
+            "enabled": true,
+            "default_permission": "allow",
+            "rules": [
+                {
+                    "id": "deny query ingress",
+                    "permission": "deny",
+                    "messages": ["query", "liveliness_token", "liveliness_query"],
```
Comment (oteffahi) [inline zenoh/tests/acl.rs:1843]: `"query"` and `"liveliness_token"` messages are not related to this test
```suggestion
                    "messages": ["liveliness_query"],
```

File: zenoh/tests/acl.rs [hunk 3]
```diff
@@ -1748,3 +1738,200 @@ async fn test_liveliness_deny_allow_query(port: u16) {
...
+        .insert_json5(
+            "access_control",
+            r#"{
+            "enabled": true,
+            "default_permission": "allow",
+            "rules": [
+                {
+                    "id": "deny query egress",
+                    "permission": "deny",
+                    "messages": ["query", "liveliness_query"],
```
Comment (oteffahi) [inline zenoh/tests/acl.rs:1800]: `"liveliness_query"` is not related to this test
```suggestion
                    "messages": ["query"],
```

File: zenoh/tests/acl.rs [hunk 4]
```diff
@@ -1748,3 +1738,200 @@ async fn test_liveliness_deny_allow_query(port: u16) {
...
+        .insert_json5(
+            "access_control",
+            r#"{
+            "enabled": true,
+            "default_permission": "allow",
+            "rules": [
+                {
+                    "id": "deny query ingress",
+                    "permission": "deny",
+                    "messages": ["query", "liveliness_query"],
```
Comment (oteffahi) [inline zenoh/tests/acl.rs:1756]: `"liveliness_query"` is not related to this test
```suggestion
                    "messages": ["query"],
```

**Review by oteffahi — CHANGES_REQUESTED** [review]
I tested the behavior and can confirm the issues are resolved.
Suggested changes in tests.

File: zenoh/tests/acl.rs (hunk 1 above)
Comment (DenisBiryukov91) [reply zenoh/tests/acl.rs]: fixed

File: zenoh/tests/acl.rs (hunk 3 above)
Comment (DenisBiryukov91) [reply zenoh/tests/acl.rs]: fixed

File: zenoh/tests/acl.rs (hunk 2 above)
Comment (DenisBiryukov91) [reply zenoh/tests/acl.rs]: fixed

File: zenoh/tests/acl.rs (hunk 4 above)
Comment (DenisBiryukov91) [reply zenoh/tests/acl.rs]: fixed

**Review by oteffahi — APPROVED** [review]
LGTM

**Comment by JEnoch** [comment]
Failing CI is not related to this PR, but to https://github.com/eclipse-zenoh/zenoh/pull/1800
